
CREATE TABLE IF NOT EXISTS activity_logs (
  log_id VARCHAR(36) DEFAULT (UUID()) PRIMARY KEY,
  employee_id VARCHAR(36) NOT NULL,
  activity_type VARCHAR(255) NOT NULL,
  description TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (employee_id) REFERENCES employees (employee_id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
